language: generic 
sudo: required
services:
    - docker

# before_install:
#     - docker build -t andymac007/lrh-test -f ./louisrielweb/Dockerfile.dev ./louisrielweb
#     # additonal test

# script:
#     - docker run -e CI=true andymac007/lrh-test npm test 


after_success:
    - docker build -t andymac007/lrh-client ./louisrielweb
    - docker build -t andymac007/lrh-server ./Server 
    - docker build -t andymac007/lrh-nginx ./nginx
    #Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #take images and push them to docker hub
    - docker push andymac007/lrh-client
    - docker push andymac007/lrh-server
    - docker push andymac007/lrh-nginx